openapi: 3.0.3
info:
  title: Airbnb APIs
  description: |-
    This contains list of endpoints that expose Airbnb to 3rd parties (....)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@airbnb.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: "api.airbnb.com" #US server
  - url: "api.eu1.airbnb.com" #EU server
  - url: "api.ap1.airbnb.com" #APAC server
tags:
  - name: listings
    description: Get deatils about listings on Airbnb
security:
  - api_key: [] 
paths:
  /listings:
    get:
      tags:
        - listings
      summary: gets a list of listings
      description: gets a list of listings
      operationId: getListings
      parameters:
        - name: minprice
          in: query
          description: minimum price
          required: false
          schema:
            type: integer
        - name: maxprice
          in: query
          description: maximum price
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listings'
        '401':
          description: Unauthorized
        '403':
          description: forbidden
        '415':
          description: Unsupported Media Type
        '429':
          description: Rate limit exceeded
    post:
      tags:
        - listings
      summary: creates a listing
      description: creates a listing using the request payload.
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Listing'
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing201'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: forbidden
        '415':
          description: Unsupported Media Type
        '429':
          description: Rate limit exceeded
  /listings/{listing-id}:
    get:
      tags:
        - listings
      summary: gets a listing by its Id
      description: gets a single listing using ID
      operationId: getListingById
      parameters:
        - name: listing-id
          in: path
          description: UUID for listing
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found  
        '415':
          description: Unsupported Media Type
        '429':
          description: Rate limit exceeded
    patch:
      tags:
        - listings
      summary: updates a listing
      description: updates a listing using the request payload.
      parameters:
        - name: listing-id
          in: path
          description: UUID for listing
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/PatchListing'
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing201'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: forbidden
        '415':
          description: Unsupported Media Type
        '429':
          description: Rate limit exceeded
components:
  schemas:
    Listings:
      type: array
      items: 
        $ref: '#/components/schemas/Listing'
    Listing:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        currency:
          type: string
          enum: ["INR", "USD", "GBP", "EUR"]
        _v:
          type: integer
      required:
        - name
        - price
        - currency
    PatchListing:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        currency:
          type: string
          enum: ["INR", "USD", "GBP", "EUR"]
        _v:
          type: integer
    Listing201:
      type: object
      properties:
        id:
          type: string
        created:
          type: boolean
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header